-- Cadastrando Estados
insert into states ("name", "acronym") values ('Acre','AC');
insert into states ("name", "acronym") values ('Alagoas','AL');
insert into states ("name", "acronym") values ('Amapá','AP');
insert into states ("name", "acronym") values ('Amazonas','AM');
insert into states ("name", "acronym") values ('Bahia','BA');
insert into states ("name", "acronym") values ('Ceará','CE');
insert into states ("name", "acronym") values ('Espírito Santo','ES');
insert into states ("name", "acronym") values ('Goiás','GO');
insert into states ("name", "acronym") values ('Maranhão','MA');
insert into states ("name", "acronym") values ('Mato Grosso','MT');
insert into states ("name", "acronym") values ('Mato Grosso do Sul','MS');
insert into states ("name", "acronym") values ('Minas Gerais','MG');
insert into states ("name", "acronym") values ('Pará','PA');
insert into states ("name", "acronym") values ('Paraíba','PB');
insert into states ("name", "acronym") values ('Paraná','PR');
insert into states ("name", "acronym") values ('Pernambuco','PE');
insert into states ("name", "acronym") values ('Piauí','PI');
insert into states ("name", "acronym") values ('Rio de Janeiro','RJ');
insert into states ("name", "acronym") values ('Rio Grande do Norte','RN');
insert into states ("name", "acronym") values ('Rio Grande do Sul','RS');
insert into states ("name", "acronym") values ('Rondônia','RO');
insert into states ("name", "acronym") values ('Roraima','RR');
insert into states ("name", "acronym") values ('Santa Catarina','SC');
insert into states ("name", "acronym") values ('São Paulo','SP');
insert into states ("name", "acronym") values ('Sergipe','SE');
insert into states ("name", "acronym") values ('Tocantins','TO');
insert into states ("name", "acronym") values ('Distrito Federal','DF');

-- Cadastrando municipios do Acre
insert into cities ("name", "state_id") values ('Acrelândia',1);
insert into cities ("name", "state_id") values ('Assis Brasil',1);
insert into cities ("name", "state_id") values ('Brasiléia',1);
insert into cities ("name", "state_id") values ('Bujari',1);
insert into cities ("name", "state_id") values ('Capixaba',1);
insert into cities ("name", "state_id") values ('Cruzeiro do Sul',1);
insert into cities ("name", "state_id") values ('Epitaciolândia',1);
insert into cities ("name", "state_id") values ('Feijó',1);
insert into cities ("name", "state_id") values ('Jordão',1);
insert into cities ("name", "state_id") values ('Mâncio Lima',1);
insert into cities ("name", "state_id") values ('Manoel Urbano',1);
insert into cities ("name", "state_id") values ('Marechal Thaumaturgo',1);
insert into cities ("name", "state_id") values ('Plácido de Castro',1);
insert into cities ("name", "state_id") values ('Porto Acre',1);
insert into cities ("name", "state_id") values ('Porto Walter',1);
insert into cities ("name", "state_id") values ('Rio Branco',1);
insert into cities ("name", "state_id") values ('Rodrigues Alves',1);
insert into cities ("name", "state_id") values ('Santa Rosa do Purus',1);
insert into cities ("name", "state_id") values ('Sena Madureira',1);
insert into cities ("name", "state_id") values ('Senador Guiomard',1);
insert into cities ("name", "state_id") values ('Tarauacá',1);
insert into cities ("name", "state_id") values ('Xapuri',1);


-- Cadastrando municipios do Alagoas
insert into cities ("name", "state_id") values ('Água Branca',2);
insert into cities ("name", "state_id") values ('Anadia',2);
insert into cities ("name", "state_id") values ('Arapiraca',2);
insert into cities ("name", "state_id") values ('Atalaia',2);
insert into cities ("name", "state_id") values ('Barra de Santo Antônio',2);
insert into cities ("name", "state_id") values ('Barra de São Miguel',2);
insert into cities ("name", "state_id") values ('Batalha',2);
insert into cities ("name", "state_id") values ('Belém',2);
insert into cities ("name", "state_id") values ('Belo Monte',2);
insert into cities ("name", "state_id") values ('Boca da Mata',2);
insert into cities ("name", "state_id") values ('Branquinha',2);
insert into cities ("name", "state_id") values ('Cacimbinhas',2);
insert into cities ("name", "state_id") values ('Cajueiro',2);
insert into cities ("name", "state_id") values ('Campestre',2);
insert into cities ("name", "state_id") values ('Campo Alegre',2);
insert into cities ("name", "state_id") values ('Campo Grande',2);
insert into cities ("name", "state_id") values ('Canapi',2);
insert into cities ("name", "state_id") values ('Capela',2);
insert into cities ("name", "state_id") values ('Carneiros',2);
insert into cities ("name", "state_id") values ('Chã Preta',2);
insert into cities ("name", "state_id") values ('Coité do Nóia',2);
insert into cities ("name", "state_id") values ('Colônia Leopoldina',2);
insert into cities ("name", "state_id") values ('Coqueiro Seco',2);
insert into cities ("name", "state_id") values ('Coruripe',2);
insert into cities ("name", "state_id") values ('Craíbas',2);
insert into cities ("name", "state_id") values ('Delmiro Gouveia',2);
insert into cities ("name", "state_id") values ('Dois Riachos',2);
insert into cities ("name", "state_id") values ('Estrela de Alagoas',2);
insert into cities ("name", "state_id") values ('Feira Grande',2);
insert into cities ("name", "state_id") values ('Feliz Deserto',2);
insert into cities ("name", "state_id") values ('Flexeiras',2);
insert into cities ("name", "state_id") values ('Girau do Ponciano',2);
insert into cities ("name", "state_id") values ('Ibateguara',2);
insert into cities ("name", "state_id") values ('Igaci',2);
insert into cities ("name", "state_id") values ('Igreja Nova',2);
insert into cities ("name", "state_id") values ('Inhapi',2);
insert into cities ("name", "state_id") values ('Jacaré dos Homens',2);
insert into cities ("name", "state_id") values ('Jacuípe',2);
insert into cities ("name", "state_id") values ('Japaratinga',2);
insert into cities ("name", "state_id") values ('Jaramataia',2);
insert into cities ("name", "state_id") values ('Jequiá da Praia',2);
insert into cities ("name", "state_id") values ('Joaquim Gomes',2);
insert into cities ("name", "state_id") values ('Jundiá',2);
insert into cities ("name", "state_id") values ('Junqueiro',2);
insert into cities ("name", "state_id") values ('Lagoa da Canoa',2);
insert into cities ("name", "state_id") values ('Limoeiro de Anadia',2);
insert into cities ("name", "state_id") values ('Maceió',2);
insert into cities ("name", "state_id") values ('Major Isidoro',2);
insert into cities ("name", "state_id") values ('Mar Vermelho',2);
insert into cities ("name", "state_id") values ('Maragogi',2);
insert into cities ("name", "state_id") values ('Marechal Deodoro',2);
insert into cities ("name", "state_id") values ('Maribondo',2);
insert into cities ("name", "state_id") values ('Mata Grande',2);
insert into cities ("name", "state_id") values ('Matriz de Camaragibe',2);
insert into cities ("name", "state_id") values ('Messias',2);
insert into cities ("name", "state_id") values ('Minador do Negrão',2);
insert into cities ("name", "state_id") values ('Monteirópolis',2);
insert into cities ("name", "state_id") values ('Murici',2);
insert into cities ("name", "state_id") values ('Novo Lino',2);
insert into cities ("name", "state_id") values ('Olho d''Água das Flores',2);
insert into cities ("name", "state_id") values ('Olho d''Água do Casado',2);
insert into cities ("name", "state_id") values ('Olho d''Água Grande',2);
insert into cities ("name", "state_id") values ('Olivença',2);
insert into cities ("name", "state_id") values ('Ouro Branco',2);
insert into cities ("name", "state_id") values ('Palestina',2);
insert into cities ("name", "state_id") values ('Palmeira dos Índios',2);
insert into cities ("name", "state_id") values ('Pão de Açúcar',2);
insert into cities ("name", "state_id") values ('Pariconha',2);
insert into cities ("name", "state_id") values ('Paripueira',2);
insert into cities ("name", "state_id") values ('Passo de Camaragibe',2);
insert into cities ("name", "state_id") values ('Paulo Jacinto',2);
insert into cities ("name", "state_id") values ('Penedo',2);
insert into cities ("name", "state_id") values ('Piaçabuçu',2);
insert into cities ("name", "state_id") values ('Pilar',2);
insert into cities ("name", "state_id") values ('Pindoba',2);
insert into cities ("name", "state_id") values ('Piranhas',2);
insert into cities ("name", "state_id") values ('Poço das Trincheiras',2);
insert into cities ("name", "state_id") values ('Porto Calvo',2);
insert into cities ("name", "state_id") values ('Porto de Pedras',2);
insert into cities ("name", "state_id") values ('Porto Real do Colégio',2);
insert into cities ("name", "state_id") values ('Quebrangulo',2);
insert into cities ("name", "state_id") values ('Rio Largo',2);
insert into cities ("name", "state_id") values ('Roteiro',2);
insert into cities ("name", "state_id") values ('Santa Luzia do Norte',2);
insert into cities ("name", "state_id") values ('Santana do Ipanema',2);
insert into cities ("name", "state_id") values ('Santana do Mundaú',2);
insert into cities ("name", "state_id") values ('São Brás',2);
insert into cities ("name", "state_id") values ('São José da Laje',2);
insert into cities ("name", "state_id") values ('São José da Tapera',2);
insert into cities ("name", "state_id") values ('São Luís do Quitunde',2);
insert into cities ("name", "state_id") values ('São Miguel dos Campos',2);
insert into cities ("name", "state_id") values ('São Miguel dos Milagres',2);
insert into cities ("name", "state_id") values ('São Sebastião',2);
insert into cities ("name", "state_id") values ('Satuba',2);
insert into cities ("name", "state_id") values ('Senador Rui Palmeira',2);
insert into cities ("name", "state_id") values ("Tanque d''Arca",2);
insert into cities ("name", "state_id") values ('Taquarana',2);
insert into cities ("name", "state_id") values ('Teotônio Vilela',2);
insert into cities ("name", "state_id") values ('Traipu',2);
insert into cities ("name", "state_id") values ('União dos Palmares',2);
insert into cities ("name", "state_id") values ('Viçosa',2);

-- Cadastrando municipios do Amapá
insert into cities ("name", "state_id") values ('Amapá',3);
insert into cities ("name", "state_id") values ('Calçoene',3);
insert into cities ("name", "state_id") values ('Cutias',3);
insert into cities ("name", "state_id") values ('Ferreira Gomes',3);
insert into cities ("name", "state_id") values ('Itaubal',3);
insert into cities ("name", "state_id") values ('Laranjal do Jari',3);
insert into cities ("name", "state_id") values ('Macapá',3);
insert into cities ("name", "state_id") values ('Mazagão',3);
insert into cities ("name", "state_id") values ('Oiapoque',3);
insert into cities ("name", "state_id") values ('Pedra Branca do Amapari',3);
insert into cities ("name", "state_id") values ('Porto Grande',3);
insert into cities ("name", "state_id") values ('Pracuúba',3);
insert into cities ("name", "state_id") values ('Santana',3);
insert into cities ("name", "state_id") values ('Serra do Navio',3);
insert into cities ("name", "state_id") values ('Tartarugalzinho',3);
insert into cities ("name", "state_id") values ('Vitória do Jari',3);

-- Cadastrando municipios de Amazonas
-- TODO Mock de Estados e Cidades